{ 
"code" : "cy",
"name" : "Cymraeg",
"translator" : "<a href=\"http://twitter.com/huwwaters\">Huw Waters</a>",
"lang" : "Newid iaith:",
"version" : "fersiwn",
"help" : "Cymorth",
"about" : "Ynghylch",
"share" : "Rhannu",
"sharewith" : "Rhannu efo",
"switchtext" : "newid i olygfa __WAVELENGTH__ o'r awyr",
"search" : "Chwilio",
"press" : "Gwasgwch __KEY__",
"close" : "Cau",
"closedesc" : "cliciwch i gau",
"switchannotation" : "dangos neu guddio __ANNOTATION__",
"showhide" : "dangos neu guddio holl ddodrefn y sgr&icirc;n (ar wah&acirc;n i'r clod)",
"up" : "egni uwch (lleihau'r donfedd)",
"down" : "egni is (cynyddu'r donfedd)",
"zoomin" : "chwyddo mewn",
"zoomout" : "chwyddo allan",
"nozoomin" : "Methu chwyddo mewn ymhellach",
"nozoomout" : "Methu chwyddo allan ymhellach",
"url" : "Yr URL am yr olygfa hon yw:",
"helpdesc" : "Dengys y Llwybr Llaethog ar hyd canol a phegwn gogleddol yr Alaeth tuag at y top. Defnyddiwch eich llygoden i lusgo'r awyr o gwmpas. Eisiau mwy o wybodaeth? <a href=\"#\" class=\"videolink\">Gwyliwch tywysiad byr</a> (yn agor yn y ffenest hon). <span class=\"keyboard\">Allweddau'r bysellfwrdd yw:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Cr&euml;wyd gan <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://www.astro.cf.ac.uk/pub/Robert.Simpson/index.html\">Rob Simpson</a>, a <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Gallwch hefyd <a href=\"http://blog.chromoscope.net/download/\">ei lawrlwytho</a> a'i redeg yn lleol.</span>",
"intro" : "Erioed wedi bod eisiau sbectol pelydr-x neu olwg uwch-ddynol? Gadawa Chromoscope i chi grwydro ein Galaeth (y Llwybr Llaethog) a'r Bydysawd pell mewn <a href=\"http://blog.chromoscope.net/data/\">amrediad o donfeddi</a> o belydrau-x i'r tonnau radio hiraf.<br /><br />Newidiwch y donfedd drwy symud y <em>llithrydd</em> yn nhop de'r sgr&icirc;n a chrwydro gan ddefnyddio eich llygoden. Am fwy o wybodaeth mae <a href=\"#\" class=\"videolink\">tywysiad fideo byr</a> neu medrwch ddarllen <a href=\"http://blog.chromoscope.net/about/\">mwy ar ein blog</a>. Os oes trafferth, cliciwch &quot;Cymorth&quot; yng ngwaelod chwith y sgr&icirc;n.<br /><br /><a href=\"http://www.astro.cardiff.ac.uk/research/instr/\"><img src=\"cardiffuni.png\" style=\"border:0px;margin: 0px 5px 5px 0px;float:left;\" /></a>Caiff Chromoscope ei ariannu'n garedig gan Grwpiau <a href=\"http://www.astro.cardiff.ac.uk/research/egalactic/\">Seryddiaeth</a> ac <a href=\"http://www.astro.cardiff.ac.uk/research/instr/\">Offeryniaeth Seryddiaeth</a> Prifysgol Caerdydd.<br style=\"clear:both;\" />",
"gal" : "http://cy.wikipedia.org/wiki/System_cyfesurynnau_galaethol",
"galcoord" : "Cyfesurynnau Galaethol",
"eq" : "http://cy.wikipedia.org/wiki/System_cyfesurynnau_cyhydeddol",
"eqcoord" : "Cyfesurynnau Cyhydeddol",
"gamma" : "Pelydr Gamma",
"xray" : "Pelydr-x",
"optical" : "Gweledol",
"halpha" : "Hydrogen &alpha;",
"nearir" : "Is-goch Agos",
"farir" : "Isgoch-Pell",
"microwave" : "Microdon",
"radio" : "Radio"
}
