{
"code" : "dk",
"name" : "Dansk",
"alignment" : "left",
"translator" : "<a href='http://www.not.iac.es/general/contact.php?s=49'>S&#248;ren Frimann</a>, <a href='http://about.me/andromedaswake'>Tom Kerss</a>",
"gamma" : "Gammastr&#229;ling",
"xray" : "R&#248;ntgenstr&#229;ling",
"optical" : "Synligt lys",
"halpha" : "Brint (H&#945;)",
"nearir" : "N&#230;rinfrar&#248;d",
"farir" : "Fjerninfrar&#248;d",
"microwave" : "Mikrob&#248;lger",
"radio" : "Radiob&#248;lger",
"labels" : "m&#230;rkater",
"intro" : "Har du nogensinde &#248;nsket dig r&#248;ntgensyn eller at kunne se som en superhelt? Det kan du med Chromoscope, som lader dig udforske vores egen galakse, M&#230;lkevejen, og universets fjerneste dele i <a href=\"http://blog.chromoscope.net/data/\">en r&#230;kke forskellige b&#248;lgel&#230;ngder</a> fra gammastr&#229;ler til de l&#230;ngste radiob&#248;lger.<br /><br />Du skifter b&#248;lgel&#230;ngden ved at bruge panelet &#248;verst til h&#248;jre p&#229; sk&#230;rmen og bruger musen til at udforske verdensrummet. Har du behov for mere information kan du se en <a href=\"#\" class=\"videolink\">kort introduktionsvideo</a> (engelsk), eller l&#230;se mere p&#229; <a href=\"http://blog.chromoscope.net/about/\">vores blog</a> (engelsk). Sidder du fast kan du klikke p&#229; \"Hj&#230;lp\" nederst til venstre p&#229; sk&#230;rmen.<br /><br /><a href=\"http://www.astro.cardiff.ac.uk/research/instr/\"><img src=\"cardiffuni.png\" style=\"border:0px;margin: 0px 5px 5px 0px;float:left;\" /></a>Chromoscope takker Cardiff Universitets grupper for <a href=\"http://www.astro.cardiff.ac.uk/research/egalactic/\">Astronomi</a> og <a href=\"http://www.astro.cardiff.ac.uk/research/instr/\">Astronomi Instrumentering</a>for &#248;konomisk st&#248;tte.<br style=\"clear:both;\" />",
"helpdesc" : "M&#230;lkevejen er det lange b&#229;nd, der kan ses midt p&#229; sk&#230;rmen, med galaksens nordpol er i toppen af billedet. Du kan bruge musen til at navigere rundt p&#229; himlen. For mere information: <a href=\"#\" class=\"videolink\">Se vores korte introduktionsvideo</a> (&#229;bner i samme vindue). <span class=\"keyboard\">Tastaturgenveje er:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Skabt af <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a> og <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Du kan ogs&#229; <a href=\"http://blog.chromoscope.net/download/\">downloade programmet</a> og k&#248;re det fra din computer.</span>",
"switchtext" : "vis himlen i __WAVELENGTH__",
"switchannotation" : "vis/skjul __ANNOTATION__",
"showhide" : "vis/skjul alle paneler",
"up" : "h&#248;jere energi (kortere b&#248;lgel&#230;ngde)",
"down" : "lavere energi (l&#230;ngere b&#248;lgel&#230;ngde)",
"help" : "Hj&#230;lp",
"about" : "Om",
"share" : "Del",
"search" : "S&#248;g",
"close" : "Luk",
"closedesc" : "klik for at lukke",
"press" : "Tryk __KEY__",
"zoomin" : "zoom ind",
"zoomout" : "zoom ud",
"galcoord" : "Galaktiske koordinater",
"gal" : "http://www.denstoredanske.dk/It,_teknik_og_naturvidenskab/Astronomi/Himmellegemernes_positioner_og_bev%C3%A6gelser/astronomiske_koordinater",
"eqcoord" : "&#198;kvatoriale koordinater",
"eq" : "http://www.denstoredanske.dk/It,_teknik_og_naturvidenskab/Astronomi/Himmellegemernes_positioner_og_bev%C3%A6gelser/astronomiske_koordinater",
"centre" : "Centrer her",
"wikisky" : "Se i Wikisky",
"wwt" : "Se i WorldWideTelescope",
"nearby" : "Objekter indenfor 10 bueminutter",
"version" : "version",
"sharewith" : "Del med",
"url" : "URL for denne side:",
"nozoomout" : "Kan ikke zoome mere ud",
"nozoomin" : "Kan ikke zoome mere ind"
}
