{
"code" : "dk",
"name" : "Dansk",
"translator" : "<a href='http://about.me/andromedaswake'>Tom Kerss</a>",
"lang" : "Change sprog:",
"version" : "version",
"help" : "Hj&aelig;lp",
"about" : "Om",
"share" : "Del",
"sharewith" : "Share it with",
"switchtext" : "switch to __WAVELENGTH__ view of the sky",
"search" : "search",
"press" : "Press __KEY__",
"close" : "Close",
"closedesc" : "click to close",
"switchannotation" : " show or hide __ANNOTATION__",
"showhide" : "show or hide all screen furniture (except the credit line)",
"up" : "higher energy (reduce the wavelength)",
"down" : "lower energy (increase the wavelength)",
"zoomin" : "zoom in",
"zoomout" : "zoom out",
"nozoomin" : "Can't zoom in any more",
"nozoomout" : "Can't zoom out any more",
"url" : "The URL for this view is:",
"helpdesc" : "The Milky Way is shown across the middle. The north pole of the Galaxy is towards the top. Use the mouse to drag the sky around. Want more info? <a href=\"#\" onClick=\"javascript:chromo_active.showVideoTour();return false;\">Watch a quick tour</a> (opens in this window). <span class=\"keyboard\">The keyboard controls are:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Created by <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a>, and <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. You can also <a href=\"http://blog.chromoscope.net/download/\">download it</a> to run locally.</span>",
"intro" : "Har du altid &oslash;nsket at have r&oslash;ntgentsyn og kunne se som en super-helt? Chromoscope lader dig udforske vores Galakse (M&aelig;lkevejen) samt det fjerne Univers i <a href=\"http://blog.chromoscope.net/data/\">en r&aelig;kke b&oslash;lgef&aelig;ngder</a> fra gammastr&aring;ling til de l&aelig;ngste raiob&oslash;lger.<br /><br />Skift b&oslash;lgel&aelig;ngden ved at bruge kontrollen &oslash;verst til h&oslash;jre p&aring; sk&aelig;rmen og udforsk Rummet med din mus. Vil du have mere information sa har vi <a href=\"#\" onClick=\"javascript:chromo_active.showVideoTour();return false;\">en hurtig video tur</a> eller du kan l&aelig;se <a href=\"http://blog.chromoscope.net/about/\">mere p&aring; vores blog</a>. Har du brug for hj&aelig;lp, s&aring; klik p&aring; “Hj&aelig;lp” nederst til venstre p&aring; sk&aelig;rmen.<br /><br /><a href=\"http://www.astro.cardiff.ac.uk/research/instr/\"><img src=\"cardiffuni.png\" style=\"border:0px;margin: 0px 5px 5px 0px;float:left;\" /></a>Chromoscope takker Cardiff Universitets <a href=\"http://www.astro.cardiff.ac.uk/research/egalactic/\">Astronomi</a> og <a href=\"http://www.astro.cardiff.ac.uk/research/instr/\">Astronomi Instrumentation</a> Grupper for deres &oslash;konomisk st&oslash;tte.<br style=\"clear:both;\" />",
"gal" : "http://en.wikipedia.org/wiki/Galactic_coordinate_system",
"galcoord" : "Galactic Coordinates",
"eq" : "http://en.wikipedia.org/wiki/Equatorial_coordinate_system",
"eqcoord" : "Equatorial Coordinates",
"gamma" : "Gamma Str&aring;ler",
"xray" : "R&oslash;ntgen Str&aring;ler",
"optical" : "Synligt",
"halpha" : "Hydrogen Alfa",
"farir" : "Fjernt - Infrar&oslash;dt",
"microwave" : "Mikrob&oslash;lger",
"radio" : "Radiob&oslash;lger",
"labels" : "Labels"
}
