{
"code" : "en",
"name" : "English",
"translator" : "",
"lang" : "Change language:",
"version" : "version",
"help" : "Help",
"about" : "About",
"share" : "Share",
"sharewith" : "Share it with",
"switchtext" : "switch to __WAVELENGTH__ view of the sky",
"search" : "search",
"press" : "Press __KEY__",
"close" : "Close",
"closedesc" : "click to close",
"switchannotation" : " show or hide __ANNOTATION__",
"showhide" : "show or hide all screen furniture (except the credit line)",
"up" : "higher energy (reduce the wavelength)",
"down" : "lower energy (increase the wavelength)",
"zoomin" : "zoom in",
"zoomout" : "zoom out",
"nozoomin" : "Can't zoom in any more",
"nozoomout" : "Can't zoom out any more",
"url" : "The URL for this view is:",
"helpdesc" : "The Milky Way is shown across the middle. The north pole of the Galaxy is towards the top. Use the mouse to drag the sky around. Want more info? <a href=\"#\" class=\"videolink\">Watch a quick tour</a> (opens in this window). <span class=\"keyboard\">The keyboard controls are:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Created by <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a>, and <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. You can also <a href=\"http://blog.chromoscope.net/download/\">download it</a> to run locally.</span>",
"intro" : "Ever wanted X-ray specs or super-human vision? Chromoscope lets you explore our Galaxy (the Milky Way) and the distant Universe in <a href=\"http://blog.chromoscope.net/data/\">a range of wavelengths</a> from gamma-rays to the longest radio waves.<br /><br />Change the wavelength using the <em>slider</em> in the top right of the screen and explore space using your mouse. For more information we have <a href=\"#\" class=\"videolink\">a quick video tour</a> or you can read <a href=\"http://blog.chromoscope.net/about/\">more on our blog</a>. If you get stuck, click &quot;Help&quot; in the bottom left.<br /><br /><a href=\"http://www.astro.cardiff.ac.uk/research/instr/\"><img src=\"cardiffuni.png\" style=\"border:0px;margin: 0px 5px 5px 0px;float:left;\" /></a>Chromoscope is kindly funded by the Cardiff University <a href=\"http://www.astro.cardiff.ac.uk/research/egalactic/\">Astronomy</a> and <a href=\"http://www.astro.cardiff.ac.uk/research/instr/\">Astronomy Instrumentation</a> Groups.<br style=\"clear:both;\" />",
"gal" : "http://en.wikipedia.org/wiki/Galactic_coordinate_system",
"galcoord" : "Galactic Coordinates",
"eq" : "http://en.wikipedia.org/wiki/Equatorial_coordinate_system",
"eqcoord" : "Equatorial Coordinates",
"gamma" : "Gamma ray",
"xray" : "X-ray",
"optical" : "Visible",
"halpha" : "Hydrogen &alpha;",
"farir" : "Far-Infrared",
"nearir" : "Near-Infrared",
"microwave" : "Microwave",
"radio" : "Radio",
"labels" : "Labels"
}
