{
"code" : "es",
"name" : "Espa&#241;ol",
"alignment" : "left",
"translator" : "Lizette Guzman Ramirez y <a href=\"http://musingsofmonkeys.blogspot.co.uk/\">Dave Jones</a>",
"gamma" : "Rayos Gamma",
"xray" : "Rayos -X",
"optical" : "Visible",
"halpha" : "Hidr&#243;geno &#945;",
"nearir" : "Infrarrojo Cercano",
"farir" : "Infrarrojo Lejano",
"microwave" : "Microondas",
"radio" : "Radio",
"labels" : "etiquetas",
"intro" : "Alguna vez quisiste tener binoculares de rayos-X o visi&#243;n super poderosa? Cromosc&#243;pio te dejar&#225; explorar nuestra Gal&#225;xia (la V&#237;a L&#225;ctea) y el Universo lejano en <a href=\"http://blog.chromoscope.net/data/\">un intervalo de longitudes de onda</a> desde los rayos-X hasta las largu&#237;simas ondas de radio.<br /><br />Cambia de longitud de onda utilizando la barra en la parte superior derecha de la pantalla y explora el espacio utilizando tu rat&#243;n. Para mayor informaci&#243;n tenemos <a href=\"#\" class=\"videolink\">un video de un tour r&#225;pido</a> o puedes leer m&#225;s en <a href=\"http://blog.chromoscope.net/about/\">nuestra pagina web</a>. Si tienes alg&#250;n problema presiona el &#237;cono de \"ayuda\" en la parte inferior izquierda de la pantalla.",
"helpdesc" : "Bienvenido a Cromosc&#243;pio, la V&#237;a L&#225;ctea se encuentra sobre el plano medio y el polo norte de la Gal&#225;xia apunta hac&#237;a arriba. Utiliza tu rat&#243;n para arrastrar el cielo alrededor.  Si quieres saber m&#225;s <a href=\"#\" class=\"videolink\">ve nuestro tour r&#225;pido</a> (abre en &#233;sta pagina). <span class=\"keyboard\">Los controles usando tu teclado son:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Creado por <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a> y <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Puedes <a href=\"http://blog.chromoscope.net/download/\">descargarlo</a> y correrlo localmente.</span>",
"switchtext" : "cambia a la visi&#243;n del cielo en __WAVELENGTH__",
"switchannotation" : "muestra o esconde __ANNOTATION__",
"showhide" : "muestra o esconde todas las etiquetas (excepto los cr&#233;ditos)",
"up" : "mayor energ&#237;a (disminuye la longitud de onda)",
"down" : "menor energ&#237;a (aumenta la longitud de onda)",
"help" : "Ayuda",
"about" : "Info",
"share" : "Comparte",
"search" : "buscar",
"close" : "Cerrar",
"closedesc" : "Pinchar aqu&#237; para cerrar",
"press" : "Presiona __KEY__",
"zoomin" : "acercar",
"zoomout" : "alejar",
"galcoord" : "Coordenadas gal&#225;cticas",
"gal" : "http://es.wikipedia.org/wiki/Coordenadas_gal%C3%A1cticas",
"eqcoord" : "Coordenadas ecuatoriales",
"eq" : "http://es.wikipedia.org/wiki/Coordenadas_ecuatoriales",
"centre" : "Centrar mapa aqu&#237;",
"wikisky" : "Ver en WikiSky",
"wwt" : "Ver en WorldWideTelescope",
"nearby" : "Objetos en un radio de 10&#8242;",
"version" : "versi&#243;n",
"sharewith" : "Compatirlo con",
"url" : "La direccion URL es:",
"nozoomout" : "No puedo alejarme m&#225;s",
"nozoomin" : "No puedo acercar m&#225;s"
}
