{
"code" : "fr",
"name" : "Fran&#231;ais",
"translator" : "<a href=\"http://www.jb.man.ac.uk/~bm/\">Bruno Maffei</a>",
"lang" : "",
"version" : "version",
"help" : "Aide",
"about" : "Information",
"share" : "Partager",
"sharewith" : "Partagez le avec",
"switchtext" :"change pour une vue __WAVELENGTH__ du ciel",
"search" : "Cerca",
"press" : "__KEY__",
"close" : "Fermer",
"closedesc" : "Fermer",
"switchannotation" : "__ANNOTATION__",
"showhide" : "Montre ou cache tous les menus",
"up" : "Plus haute &#233;nergie (plus basse longueur d'onde)",
"down" : "Plus basse &#233;nergie (plus haute longueur d'onde)",
"zoomin" : "zoom avant",
"zoomout" : "zoom arri&#232;re",
"nozoomin" : "",
"nozoomout" : "",
"url" : "L?URL de cette page est:",
"helpdesc" : "La Voie Lact&#233;e est vue par la tranche avec le pole nord de la Galaxie vers le haut. Utilisez la souris pour faire d&#233;filer le ciel. Besoin de plus d'informations? Regardez <a href=\"#\" class=\"videolink\">un tour vid&#233;o</a> (il s'ouvrira dans cette fen&#234;tre). <span class=\"keyboard\">Les contr&#244;les du clavier sont:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Cr&#233;&#233; par <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a>, et <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Vous pouvez aussi le <a href=\"http://blog.chromoscope.net/download/\">t&#233;l&#233;charger</a> pour l'ex&#233;cuter localement.</span>",
"intro" : "Avez vous toujours r&#234;v&#233; d'avoir des lunettes Rayons X ou une super-vision? Chromoscope vous permet d'explorer notre Galaxie (la Voie Lact&#233;e) et l'Univers lointain dans <a href=\"http://blog.chromoscope.net/data/\">des longueurs d'onde</a> comprises entre les Rayons X et les ondes radio.<br/ ><br />Changez la longueur d'onde en utilisant le curseur en haut et &#224; droite de la fen&#234;tre et explorez l'espace en utilisant votre souris. Pour plus d'informations nous avons <a href=\"#\" class=\"videolink\">un tour vid&#233;o</a> ou vous pouvez lire <a href=\"http://blog.chromoscope.net/about/\">notre blog</a>. Si vous &#234;tes coinc&#233;, cliquez &laquo; Aide &raquo; en bas &#224; gauche.",
"galcoord" : "coordonn&#233;es galactiques",
"gal" : "http://fr.wikipedia.org/wiki/Syst%C3%A8me_de_coordonn%C3%A9es_galactiques",
"eqcoord" : "syst&#232;me de coordonn&#233;es &#233;quatoriales",
"eq" : "http://fr.wikipedia.org/wiki/Syst%C3%A8me_de_coordonn%C3%A9es_%C3%A9quatoriales",
"gamma" : "",
"xray" : "Rayons X",
"optical" : "Visible",
"halpha" : "Hydrog&#232;ne-&alpha;",
"farir" : "IR Lointain",
"microwave" : "Micro-ondes",
"radio" : "Radio"
}
