{
"code" : "ga",
"name" : "Gaeilge",
"translator" : "Evan Keane",
"lang" : "Athraigh an teanga:",
"version" : "Leagan",
"help" : "Cabhair",
"about" : "Faoi",
"share" : "Roinn",
"sharewith" : "Seo a roinnt le",
"switchtext" : "athraigh go amharc __WAVELENGTH__ den sp&#233;ir",
"search" : "Cuardach",
"press" : "Phreas __KEY__",
"close" : "D&#250;n",
"closedesc" : "Phreas a dh&#250;nadh",
"switchannotation" : " taispe&#225;in n&#243; t&#233;igh i bhfolach __ANNOTATION__",
"showhide" : "taispe&#225;in n&#243; t&#233;igh i bhfolach gach trosc&#225;in sc&#225;ile&#225;in (seachas an l&#237;ne admh&#225;lacha)",
"up" : "fuinneamh n&#237;os &#225;irde (laghd&#250; an tonnfhad)",
"down" : "fuinneamh n&#237;os &#237;sle (m&#233;ad&#250; an tonnfhad)",
"zoomin" : "s&#250;m&#225;il isteach",
"zoomout" : "s&#250;m&#225;il amach",
"nozoomout" : "N&#237; f&#233;idir s&#250;m&#225;il amach n&#237;os m&#243;",
"nozoomin" : "N&#237; f&#233;idir s&#250;m&#225;il isteach n&#237;os m&#243;",
"url" : "An seoladh idirl&#237;n le haghaidh an radharc seo &#233;:",
"helpdesc" : "T&#225; Bealach na B&#243; Finne le feice&#225;il trasna an l&#225;r agus an thuaidh cuaille den R&#233;altra ar barr an phicti&#250;ir. &#218;s&#225;id an luch chun an sp&#233;ir a chas timpeall. N&#237;os m&#243; eolais? <a href=\"#\" class=\"videolink\">F&#233;ach ar turas f&#237;se&#225;in sciopadh</a> (i bhfuinneoig nua). <span class=\"keyboard\">T&#225; na rialuithe méarchl&#225;r:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Cruthaithe ag <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a>, agus <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. T&#225; t&#250; &#225;balta &#233; a <a href=\"http://blog.chromoscope.net/download/\">&#237;oslucht&#250;</a> nach mbeidh t&#250; ar l&#237;ne.</span>",
"intro" : "Ba mhaith leat sp&#233acla&#237; X-ray n&#243; f&#237;s dra&#237;ochta? Le Chromoscope beidh t&#250; in ann &#225;r R&#233;altra (Bealach na B&#243; Finne) agus an Cruinne i bhfad i gc&#233;in, a taisc&#233;al i <a href=\"http://blog.chromoscope.net/data/\">raon de tonnfhad</a> &#243; X-ray go dt&#237; na dtonta raidi&#243; is &#225irde.<br /><br />Athraigh an tonnfhad leis an <em>sleamhn&#225;n</em> ar barr sa c&#250;inne ar dheis den sc&#225;ile&#225;in agus sp&#225;s a taisc&#233;al le do chuid luch riamhaire. Le haghaidh n&#237;os m&#243; eolais t&#225; <a href=\"#\" class=\"videolink\">turas f&#237;se&#225;in sciopadh</a> againn. Freisin t&#225; n&#237;os m&#243; <a href=\"http://blog.chromoscope.net/about/\">ar &#225;r mblog</a>. Muna bhfuil faidbh agat phreas &quot;Cabhair&quot; sa c&#250;inne cl&#233; ar bun an leathanach.",
"gamma" : "Gamma ray",
"xray" : "X-ray",
"optical" : "Infheicthe",
"halpha" : "Hidrigine &alpha;",
"nearir" : "Infridhearg gearr",
"farir" : "Infridhearg fada",
"microwave" : "Micreathonnach",
"radio" : "Raidi&#243;"
}
