{
"code" : "it",
"name" : "Italiano",
"translator" : "<a href=\"http://twitter.com/signaleleven\">Mike</a>",
"lang" : "Cambi la lingua:",
"version" : "versione",
"help" : "Aiuto",
"about" : "Informazioni",
"share" : "Condividi",
"sharewith" : "Condividi via",
"switchtext" : "commuti alla vista cielo del __WAVELENGTH__",
"search" : "Cerca",
"press" : "Pressa __KEY__",
"close" : "Chiudi",
"closedesc" : "scatto da chiudersi",
"switchannotation" : "__ANNOTATION__",
"showhide" : "minimo/massimo",
"up" : "pi&#249; alta energia (pi&#249; breve lunghezza d'onda)",
"down" : "energia pi&#249; bassa (lunghezza d'onda pi&#249; lunga)",
"zoomin" : "zumi dentro",
"zoomout" : "zoom fuori",
"nozoomin" : "Impossibile ingrandire ulteriormente",
"nozoomout" : "Impossibile rimpicciolire ulteriormente",
"url" : "L'URL di questa vista &#232;:",
"helpdesc" : "La Via Lattea &#232; mostrata tra la met&#224; e il polo nord galattico, verso l'alto. Usa il mouse per trascinare il cielo. Vuoi altre informazioni? <a href=\"#\" class=\"videolink\">Guarda un tour veloce</a> (si apre in questa finestra). <span class=\"keyboard\">I controlli da tastiera sono:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Creato da <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a>, e <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Puoi scaricare  <a href=\"http://blog.chromoscope.net/download/\">il software</a> per eseguirlo in locale.</span>",
"intro" : "Hai mai voluto avere occhiali a raggi X o una supervista? Chromoscope ti permette di esplorare la nostra Galassia (la Via Lattea) e l'universo <a href=\"http://blog.chromoscope.net/data/\">profondo a lunghezze d'onda</a> che vanno dai raggi X alle onde radio pi&#249; lunghe.<br /><br />Muovi il cursore in alto a destra con il mouse per cambiare la lunghezza d'onda. Per maggiori informazioni consulta <a href=\"#\" class=\"videolink\">il video tour</a> (Inglese), o puoi avere ulteriori informazioni <a href=\"http://blog.chromoscope.net/about/\">sul nostro blog</a>. Se hai bisogno di aiuto, clicca su &quot;Aiuto&quot; in basso a sinistra.",
"gal" : "http://it.wikipedia.org/wiki/Sistema_di_coordinate_galattiche",
"gamma" : "",
"xray" : "Raggi X",
"optical" : "Visibile",
"halpha" : "H-alfa",
"nearir" : "Infrarosso vicino",
"farir" : "Infrarossa lunga",
"microwave" : "Microonde",
"radio" : "Radio"
}
	
