{
"code" : "pl",
"name" : "Polski",
"translator" : "<a href=\"http://www.cft.edu.pl/~lech/\">Lech Mankiewicz</a>",
"lang" : "Zmie&#324; j&#281;zyk:",
"version" : "wersja",
"help" : "Pomoc",
"about" : "O projekcie",
"share" : "Podziel si&#281; z innymi",
"sharewith" : "Podziel si&#281; z",
"switchtext" : "przejd&#378; do  __WAVELENGTH__ widoku nieba",
"search" : "szukaj",
"press" : "Naci&#347;nij __KEY__",
"close" : "Zamknij",
"closedesc" : "kliknij by zamkn&#261;&#263;",
"switchannotation" : " poka&#380; lub ukryj __ANNOTATION__",
"showhide" : "poka&#380; lub ukryj wszystko na ekranie (z wyj&#261;tkiem napis&#243;w)",
"up" : "wi&#281;ksza energia (zmniejsz d&#322;ugo&#347;&#263; fali)",
"down" : "mniejsza energia (zwi&#281;ksz d&#322;ugo&#347;&#263; fali)",
"zoomin" : "przybli&#380;",
"zoomout" : "oddal",
"nozoomin" : "Nie mo&#380;na bardziej przybli&#380;y&#263;",
"nozoomout" : "Nie mo&#380;na bardziej oddali&#263;",
"url" : "Odno&#347;nik do tego widoku to:",
"helpdesc" : "Droga Mleczna jest widoczna wzd&#322;u&#380; &#347;rodka. Biegun p&#243;&#322;nocny Galaktyki znajduje si&#281; w g&#243;rze ekranu. U&#380;yj myszy do przeci&#261;gania widoku. &#379;&#261;dny wiedzy? class=\"videolink\">Obejrzyj przewodnik</a> (w tym samym oknie). <span class=\"keyboard\">Klawiszologia:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Stworzone przez <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a>, oraz <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Mo&#380;esz r&#243;wnie&#380; <a href=\"http://blog.chromoscope.net/download/\">pobra&#263; aplikacj&#281;</a> by uruchomi&#263; j&#261; z dysku.</span>",
"intro" : "Marzy&#322;e&#347; kiedy&#347; o okularach promieniowania X lub o wzroku super-cz&#322;owieka? Chromoscope daje Ci mo&#380;liwo&#347;&#263; badania naszej Galaktyki (Drogi Mlecznej) oraz odleg&#322;ego Wszech&#347;wiata w r&#243;&#380;nych <a href=\"http://blog.chromoscope.net/data/\">d&#322;ugo&#347;ciach fali</a> od promieniowania X do najd&#322;u&#380;szych fal radiowych.<br /><br />Zmie&#324; d&#322;ugo&#347;&#263; fali u&#380;ywaj&#261;c <em>suwaka</em> w prawej g&#243;rnej cz&#281;&#347;ci ekranu i przemierzaj przestrze&#324; za pomoc&#261; myszy. Wi&#281;cej informacji znajdziesz w <a href=\"#\" class=\"videolink\">kr&#243;tkim filmie - przewodniku</a> lub na <a href=\"http://blog.chromoscope.net/about/\">naszym blogu</a>. Je&#347;li si&#281; zagubisz, kliknij &quot;Pomoc&quot; w lewym dolnym rogu ekranu.<br /><br /><a href=\"http://www.astro.cardiff.ac.uk/research/instr/\"><img src=\"cardiffuni.png\" style=\"border:0px;margin: 0px 5px 5px 0px;float:left;\" /></a>Chromoscope zosta&#322; ufundowany przez <a href=\"http://www.astro.cardiff.ac.uk/research/egalactic/\">Wydzia&#322; Astronomii</a> na Uniwersytecie w Cardiff oraz przez <a href=\"http://www.astro.cardiff.ac.uk/research/instr/\">Astronomy Instrumentation</a> Groups.<br style=\"clear:both;\" />",
"eq" : "http://pl.wikipedia.org/wiki/Uk&#322;ad_wsp&#243;&#322;rz&#281;dnych_r&#243;wnikowych",
"eqcoord" : "Wsp&#243;&#322;rz&#281;dne r&#243;wnikowe",
"gal" : "http://pl.wikipedia.org/wiki/Wsp&#243;&#322;rz&#281;dne_galaktyczne",
"galcoord" : "Wsp&#243;&#322;rz&#281;dne Galaktyki",
"gamma" : "Promieniowanie Gamma",
"xray" : "Promieniowanie X",
"optical" : "&#346;wiat&#322;o widzialne",
"halpha" : "Wod&#243;r &alpha;",
"farir" : "Podczerwie&#324;",
"microwave" : "Mikrofale",
"radio" : "Fale radiowe"
}
