{
"code" : "pt",
"name" : "Portugu&#234s",
"translator" : "Ana Cabral",
"lang" : "Mudar de l&#237ngua:",
"version" : "vers&#227o",
"help" : "Ajuda",
"about" : "Sobre",
"share" : "Partilhar",
"sharewith" : "Partilhar com",
"switchtext" : "Alterar para vista do c&#233u em __WAVELENGTH__ ",
"search" : "Procurar",
"press" : "Pressione __KEY__",
"close" : "Fechar",
"closedesc" : "Clique para fechar",
"switchannotation" : "mostrar ou esconder  __ANNOTATION__",
"showhide" : "Mostrar ou esconder todas as anota&#231&#245es no ecr&#227 (excepto a linha de creditos)",
"up" : "maior energia (reduzir o comprimento de onda)",
"down" : "menor energia (aumentar o comprimento de onda)",
"zoomin" : "Aproximar",
"zoomout" : "Afastar",
"nozoomin" : "N&#227o &#233 poss&#237vel aproximar mais",
"nozoomout" : "N&#227o &#233 poss&#237vel afastar mais",
"url" : "O URL para esta vista &#233:",
"helpdesc" : "A Via L&#225ctea est&#225 apresentada horizontalmente ao longo do centro da imagem, com o P&#243lo Norte Gal&#225ctico direccionado para o topo. Utilize o rato para arrastar o c&#233u. Mais informa&#231&#245es? <a href=\"#\" class=\"videolink\">Ver uma demonstra&#231&#227o r&#225pida</a> (abre nesta janela). <span class=\"keyboard\">Os controlos do teclado s&#227o:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Criado por <a href=\"http://www.jb.man.ac.uk/~slowe/\">Stuart Lowe</a>, <a href=\"http://www.astro.cf.ac.uk/pub/Robert.Simpson/index.html\">Rob Simpson</a>, e <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Tamb&#233m pode <a href=\"http://blog.chromoscope.net/download/\">fazer o download</a> da aplica&#231&#227o para a correr localmente.</span>",
"intro" : "Alguma vez desejou ter vis&#227o raio-X ou super-humana? O Chromoscope premite-lhe explorar a nossa Gal&#225xia (a Via L&#225ctea) e o Universo distante numa <a href=\"http://blog.chromoscope.net/data/\">s&#233rie de comprimentos de onda</a> desde raios-X at&#233 &#224s compridas ondas de r&#225dio.<br /><br />Altere o comprimento de onda usando a barra no canto superior direito do ecr&#227 e explore o espa&#231o usando o rato. Para mais informa&#231&#245es temos uma <a href=\"#\" class=\"videolink\">r&#225pida v&#237deo-demonstra&#231&#227o</a </a> ou pode consultar <a href=\"http://blog.chromoscope.net/about/\">o nosso blog</a>. Se se perder, pressione em &quot;Ajuda&quot; no canto inferior esquerdo.",
"galcoord" : "Sistema gal&#225;ctico",
"gal" : "http://pt.wikipedia.org/wiki/Sistema_gal%C3%A1ctico_de_coordenadas",
"eqcoord" : "Sistema equatorial",
"eq" : "http://pt.wikipedia.org/wiki/Sistema_equatorial_de_coordenadas",
"gamma" : "Raios Gama",
"xray" : "Raios-X",
"optical" : "Vis&#237vel",
"halpha" : "Hidrog&#233nio &alpha;",
"farir" : "Infra-Vermelhos long&#237nquos",
"microwave" : "Microondas",
"radio" : "R&#225dio"
}	
