{
"code" : "pt",
"name" : "Portugu&#234;s",
"alignment" : "left",
"translator" : "Ana Cabral",
"gamma" : "Raios Gama",
"xray" : "Raios-X",
"optical" : "Vis&#237;vel",
"halpha" : "Hidrog&#233;nio &#945;",
"nearir" : "Infravermelhos pr&#243;ximos",
"farir" : "Infravermelhos long&#237;nquos",
"microwave" : "Micro-ondas",
"radio" : "R&#225;dio",
"labels" : "Anota&#231;&#245;es",
"intro" : "Alguma vez desejou ter vis&#227;o raio-X ou super-humana? O Chromoscope premite-lhe explorar a nossa Gal&#225;xia (a Via L&#225;ctea) e o Universo distante numa <a href=\"http://blog.chromoscope.net/data/\">s&#233;rie de comprimentos de onda</a> desde raios-X at&#233; &#224;s compridas ondas de r&#225;dio.<br /><br />Altere o comprimento de onda usando a barra no canto superior direito do ecr&#227; e explore o espa&#231;o usando o rato. Para mais informa&#231;&#245;es temos uma <a href=\"#\" class=\"videolink\">r&#225;pida v&#237;deo-demonstra&#231;&#227;o</a </a> ou pode consultar <a href=\"http://blog.chromoscope.net/about/\">o nosso blog</a>. Se se perder, pressione em \"Ajuda\" no canto inferior esquerdo.",
"helpdesc" : "A Via L&#225;ctea est&#225; apresentada horizontalmente ao longo do centro da imagem, com o P&#243;lo Norte Gal&#225;ctico direccionado para o topo. Utilize o rato para arrastar o c&#233;u. Mais informa&#231;&#245;es? <a href=\"#\" class=\"videolink\">Ver uma demonstra&#231;&#227;o r&#225;pida</a> (abre nesta janela). <span class=\"keyboard\">Os controlos do teclado s&#227;o:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Criado por <a href=\"http://www.jb.man.ac.uk/~slowe/\">Stuart Lowe</a>, <a href=\"http://www.astro.cf.ac.uk/pub/Robert.Simpson/index.html\">Rob Simpson</a>, e <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Tamb&#233;m pode <a href=\"http://blog.chromoscope.net/download/\">fazer o download</a> da aplica&#231;&#227;o para a correr localmente.</span>",
"switchtext" : "Alterar para vista do c&#233;u em __WAVELENGTH__ ",
"switchannotation" : "Mostrar ou esconder  __ANNOTATION__",
"showhide" : "Mostrar ou esconder todas as anota&#231;&#245;es no ecr&#227; (excepto a linha de creditos)",
"up" : "Maior energia (reduzir o comprimento de onda)",
"down" : "Menor energia (aumentar o comprimento de onda)",
"help" : "Ajuda",
"about" : "Sobre",
"share" : "Partilhar",
"search" : "Procurar",
"close" : "Fechar",
"closedesc" : "Clique para fechar",
"press" : "Pressione __KEY__",
"zoomin" : "Aproximar",
"zoomout" : "Afastar",
"galcoord" : "Sistema de Coordenadas Gal&#225;ticas",
"gal" : "http://pt.wikipedia.org/wiki/Sistema_gal%C3%A1ctico_de_coordenadas",
"eqcoord" : "Sistema Equatorial",
"eq" : "http://pt.wikipedia.org/wiki/Sistema_equatorial_de_coordenadas",
"centre" : "Centrar mapa neste ponto",
"wikisky" : "Ver em Wikisky",
"wwt" : "Ver em WorldWideTelescope",
"nearby" : "Objectos em 10&#8242;",
"version" : "Vers&#227;o",
"sharewith" : "Partilhar com",
"url" : "O URL para esta vista &#233;:",
"nozoomout" : "N&#227;o &#233; poss&#237;vel afastar mais",
"nozoomin" : "N&#227;o &#233; poss&#237;vel aproximar mais"
}
