{
"code" : "sv",
"name" : "svenska",
"translator" : "<a href=\"http://popast.nu\">Robert Cumming</a>",
"lang" : "Byt spr&aring;k:",
"version" : "version",
"help" : "Hj&auml;lp",
"about" : "Om",
"share" : "Dela",
"sharewith" : "Dela med",
"switchtext" : "byt till himlen i __WAVELENGTH__",
"search" : "s&ouml;k",
"press" : "tryck __KEY__",
"close" : "st&auml;ng",
"closedesc" : "klicka f&ouml;r att st&auml;nga",
"switchannotation" : " visa eller d&ouml;lj __ANNOTATION__",
"showhide" : "visa eller d&ouml;lja sk&auml;rmm&ouml;blemanget (f&ouml;rutom bildbyline)",
"up" : "h&ouml;gre energi (kortare v&aring;gl&auml;ngd)",
"down" : "l&auml;gre energi (l&auml;ngre v&aring;gl&aring;ngd)",
"zoomin" : "zooma in",
"zoomout" : "zooma ut",
"nozoomin" : "Kan inte zooma l&auml;ngre in",
"nozoomout" : "Kan inte zooma l&auml;ngre ut",
"url" : "URL f&ouml;r denna vy:",
"helpdesc" : "Vintergatan visas l&auml;ngs mitten av bilden. Galaxens nordpol finns l&auml;ngst upp. Anv&auml;nd musen f&ouml;r att dra runt himlen. Vill du ha mer info? <a href=\"#\" class=\"videolink\">Titta p&aring; v&aring;r snabbtur p&aring; video</a> (&ouml;ppnar i det h&auml;r f&ouml;nstret). <span class=\"keyboard\">Du kan styra med tangentbordet:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Skapat av <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://orbitingfrog.com/blog/\">Rob Simpson</a> och <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Du kan &auml;ven <a href=\"http://blog.chromoscope.net/download/\">ladda ner</a> Chromoscope och k&ouml;ra p&aring; din dator.</span>",
"intro" : "Har du alltid velat ha r&ouml;ntgensyn? Vill du kunna se som en superhj&auml;lte? Med Chromoscope kan du utforska v&aring;r galax, Vintergatan, och det avl&auml;gsna universum som de ser ut i <a href=\"http://blog.chromoscope.net/data/\">olika v&aring;gl&auml;ngder</a> fr&aring;n gammastr&aring;lning till de l&auml;ngsta radiov&aring;gorna.<br /><br />Byt v&aring;gl&auml;ngd med kontrollen l&auml;ngst upp till h&ouml;ger p&aring; sk&auml;rmen och leta runt i rymden med datorns mus. Du kan ocks&aring; kolla v&aring;r <a href=\"#\" class=\"videolink\">lilla instruktionsvideo</a> eller l&auml;sa <a href=\"http://blog.chromoscope.net/about/\">mer p&aring; v&aring;r blogg</a>. Om n&aring;got strular, klicka klicka &quot;Hj&auml;lp&quot; l&auml;ngst ner till v&auml;nster.<br /><br /><span class=\"nokeyboard\"><b>NYHET (2010-07-05):</b> Nu har vi även med <a href=\"#\" onClick=\"javascript:simulateKeyPress('m');return false;\" title=\"Switch to the microwave view\">himlen i mikrovågor</a> tack vare data från <a href=\"http://www.esa.int/esaCP/SEMF2FRZ5BG_index_0.html\">ESA-satelliten Planck</a>.<br /><br /></span><a href=\"http://www.astro.cardiff.ac.uk/research/instr/\"><img src=\"cardiffuni.png\" style=\"border:0px;margin: 0px 5px 5px 0px;float:left;\" /></a>Chromoscope tackar Cardiffuniversitetets grupper f&ouml;r <a href=\"http://www.astro.cardiff.ac.uk/research/egalactic/\">astronomi</a> och <a href=\"http://www.astro.cardiff.ac.uk/research/instr/\">astronomisk instrumentering</a> f&ouml;r ekonomiskt st&ouml;d.<br style=\"clear:both;\" />",
"gal" : "http://www.ne.se/lang/astronomiska-koordinater",
"galcoord" : "galaktiska koordinatsystemet",
"eq" : "http://www.ne.se/lang/astronomiska-koordinater",
"eqcoord" : "ekvatorns koordinatsystem",
"gamma" : "gammastr&aring;lning",
"xray" : "r&ouml;ntgenstr&aring;lning",
"optical" : "synligt ljus",
"halpha" : "v&auml;te (H &alpha;)",
"nearir" : "kortv&#229;gigt infrar&#246;tt",
"farir" : "l&aring;ngv&aring;gigt infrar&ouml;tt",
"microwave" : "mikrov&aring;gor",
"radio" : "radiov&aring;gor",
"labels" : "etiketter",
"centre" : "Centrera kartan h&auml;r",
"wikisky" : "Se i Wikisky",
"wwt" : "Se med WorldWideTelescope",
"nearby" : "Objekt inom 10 b&aring;gminuter"
}
