{
"code" : "es",
"name" : "Espa&#241;ol",
"translator" : "Lizette Guzman Ramirez",
"lang" : "Change language:",
"version" : "versi&#243;n",
"help" : "Ayuda",
"helpmenu" : "muestra o esconde este men&#250; de ayuda",
"about" : "Info",
"share" : "Comparte",
"sharewith" : "Compatirlo con",
"switchtext" : "cambia a la visi&#243;n del cielo en __WAVELENGTH__",
"search" : "buscar",
"press" : "Presiona __KEY__",
"close" : "Cerrar",
"closedesc" : "Click aqui para cerrar",
"switchannotation" : "muestra o esconde __ANNOTATION__",
"showhide" : "muestra o esconde todas las etiquetas (excepto los cr&#233;ditos)",
"up" : "mayor energ&#237;a (disminuye la longitud de onda)",
"down" : "menor energ&#237;a (aumenta la longitud de onda)",
"zoomin" : "acercar",
"zoomout" : "alejar",
"nozoomin" : "No puedo acercar m&#225;s ",
"nozoomout" : "No puedo alejarme m&#225;s",
"url" : "La direccion URL es:",
"helpdesc" : "Bienvenido a Cromosc&#243;pio, la V&#237;a L&#225;ctea se encuentra sobre el plano medio y el polo norte de la Gal&#225;xia apunta hac&#237;a arriba. Utiliza tu rat&#243;n para arrastrar el cielo alrededor.  Si quieres saber m&#225;s <a href=\"#\" onClick=\"javascript:chromo_active.showVideoTour();\">ve nuestro tour r&#225;pido</a> (abre en &#233;sta pagina). <span class=\"keyboard\">Los controles usando tu teclado son:<ul class=\"chromo_controlkeys\"></ul></span><span class=\"nokeyboard\"><ul class=\"chromo_controlbuttons\"></ul></span> <span class=\"keyboard\">Creado por <a href=\"http://www.strudel.org.uk/\">Stuart Lowe</a>, <a href=\"http://www.astro.cf.ac.uk/pub/Robert.Simpson/index.html\">Rob Simpson</a> y <a href=\"http://www.astro.cardiff.ac.uk/contactsandpeople/?page=full&id=493\">Chris North</a>. Puedes <a href=\"http://blog.chromoscope.net/download/\">descargarlo</a> y correrlo localmente.</span>",
"intro" : "Alguna vez quisiste tener binoculares de rayos-X o visi&#243;n super poderosa? Cromosc&#243;pio te dejar&#225; explorar nuestra Gal&#225;xia (la V&#237;a L&#225;ctea) y el Universo lejano en <a href=\"http://blog.chromoscope.net/data/\">un intervalo de longitudes de onda</a> desde los rayos-X hasta las largu&#237;simas ondas de radio.<br /><br />Cambia de longitud de onda utilizando la barra en la parte superior derecha de la pantalla y explora el espacio utilizando tu rat&#243;n. Para mayor informaci&#243;n tenemos <a href=\"#\" onClick=\"javascript:chromo_active.showVideoTour();\">un video de un tour r&#225;pido</a> o puedes leer m&#225;s en <a href=\"http://blog.chromoscope.net/about/\">nuestra pagina web</a>. Si tienes alg&#250;n problema presiona el &#237;cono de &quot;ayuda&quot; en la parte inferior izquierda de la pantalla.",
"gal" : "http://es.wikipedia.org/wiki/Coordenadas_gal%C3%A1cticas",
"galcoord" : "Coordenadas gal&aacute;cticas",
"gamma" : "Rayos Gamma",
"xray" : "Rayos -X",
"optical" : "Visible",
"halpha" : "Hidr&#243;geno &alpha;",
"farir" : "Lejano IR",
"microwave" : "Microondas",
"radio" : "Radio",
"labels" : "etiquetas"
}